Added accordion and main page
js-tasks-ru/htmlcss-20220120_marina-kozlova pull request #4
Opened 2022-02-05 15:32 UTC by ksmarina

2022-02-05 15:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-05 16:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-07 21:38 UTC, GSemikozov requested changes

2022-02-07 21:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
жестко лучше не фиксировать ширину (на мобилке сразу будет плохо)

2022-02-07 21:38 UTC, GSemikozov commented on components/container/container.css
> +    padding-left: 160px;
лишнее. Либо как задел на будущее - padding: 0 15px + box-sizing: border-box

2022-02-07 21:38 UTC, GSemikozov commented on components/container/container.css
> +    margin: auto 0;
наоборот)
margin: 0 auto;

2022-02-07 21:38 UTC, GSemikozov commented on components/footer/footer.css
> +    padding-top: 72px;
снизу тоже потребуется

2022-02-12 11:45 UTC, ksmarina commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
Removed

2022-02-12 11:49 UTC, ksmarina commented on components/container/container.css
> +    padding-left: 160px;
Исправила

2022-02-12 11:49 UTC, ksmarina commented on components/container/container.css
> +    margin: auto 0;
Исправила

2022-02-12 11:49 UTC, ksmarina commented on components/footer/footer.css
> +    padding-top: 72px;
Исправила

2022-02-13 20:48 UTC, GSemikozov approved these changes

2022-02-13 20:48 UTC, merged