Skeleton
js-tasks-ru/htmlcss-20220120_marina-kozlova pull request #5
Opened 2022-02-05 17:36 UTC by ksmarina

2022-02-05 17:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-05 20:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-07 21:39 UTC, GSemikozov requested changes

2022-02-07 21:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ни высоту, ни ширину лучше не фиксировать, чтобы компонент был гибким и мог подстраиваться под любой контекст

2022-02-07 21:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 50%;
лишнее - пусть высоту определяет внутреннее содержимое (может быть 2 линии, а может и 10)

2022-02-12 11:42 UTC, ksmarina commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 50%;
Done

2022-02-12 11:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-12 11:42 UTC, ksmarina commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
done

2022-02-12 11:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-13 20:48 UTC, GSemikozov approved these changes

2022-02-13 20:48 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-02-13 20:52 UTC, GSemikozov approved these changes

2022-02-13 20:52 UTC, merged